apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devops-ci-api-netpol
  namespace: devops-app
spec:
  podSelector:
    matchLabels:
      app: devops-ci-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: devops-app
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53  # DNS
    - protocol: UDP
      port: 53  # DNS
  - to:
    - namespaceSelector: {}
